version: "3"

services:
  spring-native-image:
    image: ghcr.io/graalvm/native-image:muslib-ol9-java17
    volumes:
      - ./jar:/jar
      - ./script:/script
      - ./target:/target
    entrypoint: "/script/run.sh"
